version: '3.1'
services:
  game:
    image: joshhsoj1902/linuxgsm-docker:latest
    environment:
      - LGSM_GAMESERVERNAME=cssserver
      - LGSM_DEFAULT_CFG_DIRNAME=CounterStrikeSource
      - LGSM_UPDATEINSTALLSKIP=AUTO
      - LGSM_PORT=27015

